### ISSUE TITLE
gedit plugins folder location varies from different versions of Ubuntu

### ISSUE THREAD

**Issue by alevis** [alanhamlett/gedit-hilight#1]
`/.gnome2/gedit/plugins` 
doesn't exist in my case since i'm using **Ubuntu 14.04**
Can you add the directories for different versions of Ubuntu?

:+1:  **Ubuntu 14.04** the gedit plugins folder is at `/usr/lib/x86_64-linux-gnu/gedit/plugins/`
or `/usr/lib/i386-linux-gnu/gedit/plugins/` for 32-bit systems.

**Comment by alanhamlett** [comment]
Thanks for the PR, closing this issue after merging #2.
